# Generated by Django 3.2.9 on 2022-05-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_report', '0002_auto_20220529_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_report_problem',
            name='allocated_room',
        ),
    ]
