# Generated by Django 3.2.9 on 2022-05-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_report', '0003_remove_student_report_problem_allocated_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_report_problem',
            name='feedback',
            field=models.BooleanField(default=0),
        ),
    ]
