# Generated by Django 3.2.9 on 2022-06-05 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_allocate_block_allocate_room'),
        ('problems_report', '0005_alter_student_report_problem_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_report_problem',
            name='allocation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hostel.allocate_room'),
        ),
    ]
