# Generated by Django 3.2.9 on 2022-06-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_report', '0006_student_report_problem_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_report_problem',
            name='allocation',
        ),
    ]
