# Generated by Django 3.2.9 on 2022-06-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_report', '0007_remove_student_report_problem_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden_report_problem',
            name='feedback',
            field=models.IntegerField(default=0),
        ),
    ]
