# Generated by Django 3.2.9 on 2022-06-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_allocate_block_allocate_room'),
        ('problems_report', '0008_warden_report_problem_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_report_problem',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='student_report_problem',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='student_report_problem',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='warden_report_problem',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='warden_report_problem',
            name='hostel',
        ),
        migrations.AddField(
            model_name='student_report_problem',
            name='allocateroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hostel.allocate_room'),
        ),
    ]
