# Generated by Django 3.2.9 on 2022-06-22 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_allocate_block_allocate_room'),
        ('problems_report', '0010_auto_20220622_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warden_report_problem',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='warden_report_problem',
            name='hostel',
        ),
        migrations.AddField(
            model_name='warden_report_problem',
            name='allocateblock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hostel.allocate_block'),
        ),
    ]
